services:
  bfa-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bfa-gateway
    image: sandrog77/bfa-gateway:latest
    ports:
      - "8000:8000"
    environment:
      - BFA_USE_MOCK_EMBEDDINGS=true
      - BFA_USE_OPENAI_EMBEDDINGS=false
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    networks:
      - irca

networks:
  irca:
    external: true
